services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: british_english_academy_esl
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
  web:
    build: .
    depends_on: [db]
    ports:
      - "3000:3000"
    env_file: .env
volumes:
  pgdata:
